config/routes.rb
class CustomDomain
  def matches?(request)
    return false if request.subdomain.length <= 0 || request.subdomain == 'www'
    true
  end
end

Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'sessions',
    registrations: "registrations",
    omniauth_callbacks: "omniauth_callbacks"
  }
  
  authenticate :user do
    resources :canvas_loads do
      member do
        get :setup_course
      end
    end
    root :to => "canvas_loads#new", as: "root"
  end

  resources :users
  resources :canvas_authentications

end

app/controllers/canvas_loads_controller.rb
class CanvasLoadsController < ApplicationController
  include ActionController::Live
  
  Mime::Type.register "text/event-stream", :stream

  before_action :set_canvas_load, only: [:show, :setup_course]

  def index
    @canvas_loads = current_user.canvas_loads
  end

  def show
  end

  def new
    auth = current_user.authentications.find_by(provider: 'canvas')
    @is_instructure_admin = CanvasWrapper.is_instructure_admin(auth.token)
    @canvas_load = CanvasLoad.new(courses: sample_courses)
  end

  def create
    @canvas_load = current_user.canvas_loads.build(canvas_load_params)
    @canvas_load.canvas_domain = current_user.authentications.find_by(provider: 'canvas').provider_url
    if @canvas_load.save    
      render :create
    else
      render :new
    end
  end

  def setup_course

    subaccount_name = 'Canvas Demo Courses'
    response.headers['Content-Type'] = 'text/event-stream'
    sub_account_id = nil
    valid_teacher = false
    enrollments = {}
    course_urls = {}

    # For now just set this to false. Later if we want to add an option to the UI we can allow
    # users to be enrolled in existing courses not just the courses that were added in this iteration.
    enroll_in_existing_courses = false

    # We can update existing courses if we want to add an option to the UI. For now just create new ones. 
    always_create_courses = true

    begin
      response.stream.write "Starting setup...\n\n"
      response.stream.write "Go get yourself a tasty beverage. This will take a while...\n\n"
      if @canvas_load.sis_id.present?
        response.stream.write "Checking sisID...\n\n"
        if valid_teacher = @canvas_load.check_sis_id
          response.stream.write "Found valid user for teacher role.\n\n"
        else
          response.stream.write "Found no valid user for teacher role.\n\n" 
        end
      end

      if sub_account = @canvas_load.find_or_create_sub_account(subaccount_name)
        sub_account_id = sub_account[:sub_account]['id']
        if sub_account[:existing]
          response.stream.write "Found Existing Sub Account #{subaccount_name}-------------------------------\n\n"
        else
          response.stream.write "Adding Sub Account -------------------------------\n\n"
          response.stream.write "Added sub account: #{subaccount_name}.\n\n"
        end
      else
        response.stream.write "You don't have permissions to add subaccount: #{subaccount_name}. Courses will be added to your default account.\n\n"
      end

      if @canvas_load.course_welcome
        response.stream.write "Checking for existing 'Welcome to Canvas' course.\n\n"
        if @canvas_load.setup_welcome(sub_account_id)
          response.stream.write "Preparing to create 'Welcome to Canvas' course.\n\n"
        else
          response.stream.write "Found a 'Welcome to Canvas' course -- won't create another.\n\n"
        end
      end

      response.stream.write "Adding Users -------------------------------\n\n"
      users = {}
      sample_users.each do |user|
        result = @canvas_load.find_or_create_user(user, sub_account_id)
        if result[:user] 
          users[user[:email]] = result[:user]
          if result[:existing]
            response.stream.write "Found existing user: #{user[:name]}.\n\n"
          else
            response.stream.write "Added user: #{user[:name]}.\n\n"
          end
        elsif result[:error]
          response.stream.write "Error adding #{user[:name]}: #{result[:error]}\n\n"
        else
          response.stream.write "Couldn't find or add #{user[:name]}\n\n"
        end
      end

      response.stream.write "Adding Courses -------------------------------\n\n"
      courses = {}
      migrations = {}
      @canvas_load.courses.each do |course|
        result = @canvas_load.find_or_create_course(course, sub_account_id, always_create_courses)
        sis_id = course.sis_course_id || 'welcome' # The welcome course returns a null sis id.
        courses[sis_id] = result[:course]
        migrations[sis_id] = result[:migration] if result[:migration]
        if result[:existing]
          response.stream.write "#{course.name} already exists.\n\n"
        else
          response.stream.write "Added course: #{course.name}.\n\n"
        end
      end

      if users.present?
        response.stream.write "Adding Enrollments -------------------------------\n\n"
        
        if valid_teacher
          courses.each do |sis_course_id, course|
            @canvas_load.ensure_enrollment(valid_teacher['id'], course['id'], 'teacher')
            response.stream.write "Enrolled #{valid_teacher[:name]} in #{course['course_code']}\n\n"
          end
        end

        samples('enrollments').each do |enrollment|

          if user = users[enrollment[:email]]
            sis_course_id = enrollment[:sis_course_id]
            course = courses[sis_course_id]

            if !course && enroll_in_existing_courses
              if course = @canvas_load.find_course_by_course_code(sub_account_id, sis_course_id)
                courses[sis_course_id] = course
              end
            end

            if course
              course_code = course['course_code']
              begin
                @canvas_load.ensure_enrollment(user['id'], course['id'], enrollment[:type])
                response.stream.write "Enrolled #{enrollment[:name]} (#{enrollment[:email]}) in #{course_code}\n\n"
                enrollments[sis_course_id] ||= []
                enrollments[sis_course_id] << user
              rescue Canvas::ApiError => ex
                response.stream.write "Error #{enrollment[:name]} (#{enrollment[:email]}) in #{course_code}: #{ex}\n\n"
              end
            else
              if enroll_in_existing_courses
                response.stream.write "Could not enroll #{enrollment[:name]} (#{enrollment[:email]}). #{sis_course_id} not available.\n\n"
              end
            end
          else
            response.stream.write "Could not find #{enrollment[:name]} (#{enrollment[:email]}) to enroll in #{sis_course_id}\n\n"
          end
        end
      end
    
      # Setup LTI tools
      if sub_account_id
        courses.each do |sis_course_id, course|
          if @canvas_load.lti_attendance
            params = @canvas_load.lti_tool_params(
              Rails.application.secrets.lti_attendance_key, 
              Rails.application.secrets.lti_attendance_secret, 
              'https://rollcall.instructure.com/configure.xml')
            tool = @canvas_load.add_lti_tool(params, course['id'], sub_account_id)
            response.stream.write "Added Attendance LTI tool to #{course['course_code']}\n\n"
          end
          if @canvas_load.lti_chat
            params = @canvas_load.lti_tool_params(
              Rails.application.secrets.lti_chat_key,
              Rails.application.secrets.lti_chat_secret, 
              'https://chat.instructure.com/lti/configure.xml')
            tool = @canvas_load.add_lti_tool(params, course['id'], sub_account_id)
            response.stream.write "Added Chat LTI tool to #{course['course_code']}\n\n"
          end
        end
      end

      completed_courses = {}
      while completed_courses.keys.length < migrations.keys.length
        migrations.each do |sis_course_id, migration|
          if completed_courses[sis_course_id].blank?
            course_code = courses[sis_course_id]['course_code']
            progress = @canvas_load.check_progress(migration)
            case progress['workflow_state']
            when 'queued'
              response.stream.write "#{course_code} is queued.\n\n"
            when 'running'
              response.stream.write "#{course_code} is #{progress['completion']}% complete. #{progress['message']}\n\n"
            when 'completed'
              completed_courses[sis_course_id] = true
              response.stream.write "#{course_code} is ready\n\n"
              course_urls[course_code] = "#{@canvas_load.canvas_domain}/courses/#{courses[sis_course_id]['id']}"
            when 'failed'
              completed_courses[sis_course_id] = true
              response.stream.write "Failed to add content to #{course_code}.\n\n"
            else
              response.stream.write "#{course_code} entered an unknown state.\n\n"
            end
          end
        end
        sleep(5)
      end

      ['discussions', 'assignments', 'quizzes', 'conversations'].each do |type|
        response.stream.write "Adding #{type} -------------------------------\n\n"
        items = samples(type)
        
        case type
        when 'discussions'
          items = items.sort_by{|i| (i[:reply] || 'n').downcase} # Put all the 'n' records first. These should be the root posts.
        end
        
        items.each do |item|
          if course = courses[item[:sis_course_id]]
            case type
            when 'discussions'
              if user = users[item[:user_id]]
                result = @canvas_load.create_discussion(user['id'], course['id'], item)
                response.stream.write "Added #{item[:title]}\n\n" if result['id']
              else
                response.stream.write "Can't find user #{item[:user_id]}\n\n"
              end
            when 'assignments'
              if user = users[item[:user_id]]
                result = @canvas_load.create_assignment_submission(user['id'], course['id'], item)
                if result['id']
                  response.stream.write "Added #{item[:name]}\n\n"
                else
                  response.stream.write "#{result[:error]}\n\n"
                end
              end
            when 'quizzes'
              #result = @canvas_load.create_quiz(course['id'], item)
            
            when 'conversations'
              if user = users[item[:user_id]]
                result = @canvas_load.create_conversation(user['id'], course['id'], item)

app/views/canvas_loads/_canvas_load.html.erb
<tr>
  <td><%= canvas_load.created_at %></td>
</tr>

app/views/canvas_loads/_common_cartridge_courses.html.erb
<%= f.fields_for :cartridge_courses do |cc| %>
  <div class="col-sm-4">
    <div class="checkbox">
      <%= cc.check_box :is_selected %>
      <%= cc.hidden_field :content %>
      <%= cc.label :cartridge_courses, cc.object.name %>
    </div>
  </div>
<% end %>

app/views/canvas_loads/_courses.html.erb
<%= f.fields_for :courses do |cc| %>
  <div class="col-sm-4">
    <div class="checkbox">
      <%= cc.label :is_selected do %>
        <%= cc.check_box :is_selected %>
        <%= cc.object.name %>
        <%= cc.hidden_field :content %>
      <% end -%>
    </div>
  </div>
<% end %>

app/views/canvas_loads/_form.html.erb
<%= form_for(@canvas_load) do |f| %>
  <%= render partial: 'layouts/errors', object: @canvas_load, as: :check_me %>
  <h1 class="text-center">Canvas Demo Loader</h1>
  <div class="container">

  <hr>

  <form class="form-horizontal" role="form">

    <% if @is_instructure_admin -%>
      <h3 class="text-info">What LTI tools do you need?</h3>
      <p class="text-muted">LTI tools will <em>not</em> be created if they already exist in this Account.</p>

      <div class="row">
        <div class="col-sm-3">
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-12">
            <div class="checkbox">
              <%= f.check_box :lti_attendance, {checked: true} %>
              <%= f.label :lti_attendance, "Roll Call Attendance" %>
            </div>
          </div>
        </div>
        </div>
        <div class="col-sm-3">
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-12">
            <div class="checkbox">
            <%= f.check_box :lti_chat, {checked: true} %>
            <%= f.label :lti_chat, "Canvas Chat" %>
            </div>
          </div>
        </div>
        </div>
      </div>
    
      <hr>
    <% end -%>

    <h3 class="text-info">Do you want to make demo courses for a specific human?</h3>
    <div class="row">
      <div class="form-group col-sm-8">
        <%= f.label :user_id, "Teacher sisID", :class => "col-sm-3 control-label" %>
        <div class="col-sm-6">
         <%= f.text_field :sis_id, :class => "form-control"%>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-sm-8">
        <%= f.label :suffix, "Suffix (e.g. lastname)", :class => "col-sm-3 control-label" %>
        <div class="col-sm-6">
         <%= f.text_field :suffix, :class => "form-control"%>
        </div>
      </div>
    </div>

    <hr>

    <h3 class="text-info">What demo courses do you want to make?</h3>

    <div class="row">
      <div class="col-sm-3">
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-12">
            <div class="checkbox">
            <%= f.check_box :course_welcome  %>
            <%= f.label :course_welcome, "Welcome to Canvas" %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <p class="text-muted">Welcome to Canvas will <em>not</em> be created if it already exists in this Account.</p>
    <hr>
    <div class="row">
      <div class="col-sm-9">
        <h3 class="text-info">Available Courses</h3>
        <%= render partial: 'canvas_loads/courses', locals: { courses: @courses, f: f} %>
      </div>
    </div>

    <%#
    <fieldset>
      <legend>What student activity do you want in the courses?</legend>
      <p class="comment">Choosing any of these options will first create and enroll fake students into the above courses.</p>
      <div><input disabled type="checkbox" name="doactivity[]" id="do-assignments" value="assignments" checked /><label for="do-assignments">Assignment submissions</label></div>
      <div><input disabled type="checkbox" name="doactivity[]" id="do-introductions" value="introductions" checked /><label for="do-introductions">Discussion introductions</label></div>
      <div><input disabled type="checkbox" name="doactivity[]" id="do-discussions" value="discussions" checked /><label for="do-discussions">Class discussions</label></div>
      <div><input disabled type="checkbox" name="doactivity[]" id="do-conversations" value="conversations" checked /><label for="do-conversations">Random conversation msg</label></div>
    </fieldset>
    %>

    <br/>
    <div class="row">

      <div class="col-sm-2">
      <%= f.submit "Submit", class: "btn btn-info btn-lg btn-block" %>
      </div>
    </div>
    </form>

  </div>
<% end %>

app/views/canvas_loads/create.html.erb
<h2>Setting up your Canvas course</h2>
<iframe src="<%= setup_course_canvas_load_path(@canvas_load) %>" style="border:none;width:100%;height:4000px;"></iframe>

app/views/canvas_loads/edit.html.erb
<%= render 'form' %>

app/views/canvas_loads/index.html.erb
<%= link_to "Setup Demo Course", new_canvas_load_path %>
<h2>Activity Log</h2>
<table class="table table-striped">
  <%= render @canvas_loads %>
</table>

app/views/canvas_loads/new.html.erb
<%= render 'form' %>

app/views/canvas_loads/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_canvas_load_path(@canvas_load) %> |
<%= link_to 'Back', canvas_loads_path %>